# Generated by Django 3.2.8 on 2022-04-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobileno',
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
