# Generated by Django 3.2.8 on 2022-04-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20220416_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
    ]
