# Generated by Django 3.2.8 on 2022-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
