# Generated by Django 3.2.8 on 2022-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_contact_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('security', models.CharField(max_length=122)),
                ('cnf', models.CharField(max_length=122)),
            ],
        ),
    ]
