# Generated by Django 3.2.8 on 2022-07-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='learn/%y')),
            ],
        ),
    ]
