# Generated by Django 3.2.8 on 2022-07-21 05:32

from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='urls',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
