# Generated by Django 3.2.8 on 2022-07-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_video_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
